name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Frontend Tests
  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('./front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install Dependencies
        working-directory: ./front
        run: npm ci

      - name: Run Tests
        working-directory: ./front
        run: npm test -- --coverage

      - name: Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: front-coverage-report
          path: ./front/coverage

  # Backend Tests
  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ./backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('./backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Debug Installed Dependencies
        working-directory: ./backend
        run: npm ls

      - name: Run Tests
        working-directory: ./backend
        run: npm test -- --coverage

      - name: Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage-report
          path: ./backend/coverage

  # Frontend Build
  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: frontend-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ./front/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('./front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Install Dependencies
        working-directory: ./front
        run: npm ci

      - name: Build Frontend
        working-directory: ./front
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./front/build

  # Backend Build
  backend-build:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: backend-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ./backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('./backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Build Backend
        working-directory: ./backend
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: ./backend/build
